- project:
    check:
      jobs:
        - ansible-test-network-integration-vyos-python27
        - ansible-test-network-integration-vyos-python35
        - ansible-test-network-integration-vyos-python36
        - ansible-test-network-integration-vyos-python37
        - ansible-tox-linters
    gate:
      jobs:
        - ansible-test-network-integration-vyos-python27
        - ansible-test-network-integration-vyos-python35
        - ansible-test-network-integration-vyos-python36
        - ansible-test-network-integration-vyos-python37
        - ansible-tox-linters
